### ISSUE TITLE
[Android Qt] Call packagedependencies-android.txt

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/builddefs-qmake#1]
While using Qt Android component and a clang kit for Android : `packagedependencies-android.txt` is ignored during qmake (`packagedependencies-linux.txt` is read instead)

* [Temp hack] : Replace content of packagedependencies for Linux/Unix with Android

![image](https://user-images.githubusercontent.com/22341309/85113528-b6421f00-b217-11ea-9720-3e0f7ecc32dc.png)
*packagedependencies-android.txt*
`opencv|4.1.1|opencv|thirdParties@github|https://github.com/SolarFramework/binaries/releases/download`

**Comment by Firefly35** [comment]
Fixed in release 4.6.2: https://github.com/b-com-software-basis/builddefs-qmake/tree/4.6.2
