### ISSUE TITLE
Ill-formed compilation database generated by QtCreator when -isystem is used

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/builddefs-qmake#13]
**HOW TO REPRODUCE**
* `git clone https://github.com/SolarFramework/SolARFramework.git -b develop && cd SolARFramework && git checkout be919630e0b6d1192f4278707bdf78453a4ec48e`
* Open QtCreator and open `SolARFramework.pro`
* Go to _projects_ tab, and select _run_ for _qmake_system()_
* Build project and then generate compilation database:  _Build -> Run Generator -> Generate Compilation Database_
* The location of the generated compilation database should be indicated in the _Genera Messages_ window. This should be something like `../build-SolARFramework-Desktop_Qt_6_5_3_GCC_64bit-Release/compile_commands.json`

**EXPECTED BEHAVIOR**
In the `arguments` array of the generated JSON file, include directory for xpcf should be:
```
-isystem/home/jmhenaff/.remaken/packages/linux-gcc/xpcf/2.7.0/interfaces
```
As XPCF is a third party library.

**OBSERVED BEHAVIOR**
Path to include dir is ill-formed:
```
-I-isystem/home/jmhenaff/.remaken/packages/linux-gcc/xpcf/2.7.0/interfaces
```

OS: Linux Ubuntu 22.04
XPCF: 2.7.0 (static)
remaken: 1.10.0
Qt Creator: 11.0.2
Qt: 6.4.3

**Comment by stefled** [comment]
The QtCreator Compilation Database generation commands does not handle the different compilation flags well as long as there are –isystem.
It's an external issue.
