### ISSUE TITLE
packageignoreinstall.txt is not updated in .build-rules/ if deleted or made empty

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/builddefs-qmake#15]
**HOW TO REPRODUCE**
* take a project with a non empty `packageignoreinstall.txt`
* build and observe that content of `packageignoreinstall.txt` and `.build-rules/linux-gcc-x86_64/packageignoreinstall.txt` matches
* delete file or only content of `packageignoreinstall.txt`
* rebuild

**EXPECTED BEHAVIOR**
* `.build-rules/linux-gcc-x86_64/packageignoreinstall.txt` is empty or deleted, according to what was done previously.

**OBSERVED BEHAVIOR**
* Content of `.build-rules/linux-gcc-x86_64/packageignoreinstall.txt` is the same as before deletion of file or content.

Ubuntu 22.04
remaken 1.10.0 (pre-release)

**Comment by stefled** [comment]
issue reproduced in builddefs/qmake

solution : 
- always regenerate `.build-rules/linux-gcc-x86_64/packageignoreinstall.txt` file when running qmake or rebuild even if packageignoreinstall.txt doesn't exist. 
=>`.build-rules/linux-gcc-x86_64/packageignoreinstall.txt` file will always exist, but can be empty. 

will be available in a next release
