### ISSUE TITLE
[Windows][.symlink] Build looping

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/builddefs-qmake#2]
**Only on Windows**, while using Android kit on Qt creator : 

* Open a SolARModule (ie: SolARModuleOpenCV)
* Select to deploy on Android kit
* qmake
* build --> **infinite loop**, see `compile output`

**[Temp hack] :** remove `%REMAKEN_PKG_ROOT%/rules/.symlink` and rename directory `qmake-buildefs` to `qmake` then clean and qmake again and build step should works

**Comment by stefled** [comment]
not reproduced with :
- Dell Precision 7550 - Windows 10
- Android : SDK Version: 2.1, NDK Version: 21.1.6352462 (installed by default with QtCreator)
- QT Kit : Qt 5.13.2 for Android ARM64-v8a and Qt 5.15.1 for Android
- SolARModuleOpenCV, SolARFramework

**Comment by stefled** [comment]
not reproduced
