### ISSUE TITLE
[Make] Install/Install_deps behavior

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/builddefs-qmake#3]
If we are using make arguments `install_deps` and there aren't any dependencies for this project make step return an empty build.

==> **`install_deps` should call `install`  --even when his build is empty--**

![image](https://user-images.githubusercontent.com/22341309/94026823-73658980-fdba-11ea-9045-c75610bc1f26.png)

**Comment by stefled** [comment]
already fix in a previous version
